version: '2.1'
services:
  db:    
    image: db:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres    
    ports:
    - "5555:5432"
  svc-coupon:
    image: svc-coupon:latest
    ports:
    - 9092:9092
    container_name: svc-coupon
    depends_on:
    - db