// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/coupon.proto

package coupon

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coupon_CouponType int32

const (
	Coupon_UNDEFINED Coupon_CouponType = 0
	Coupon_PERCENT   Coupon_CouponType = 1
	Coupon_FLAT      Coupon_CouponType = 2
)

var Coupon_CouponType_name = map[int32]string{
	0: "UNDEFINED",
	1: "PERCENT",
	2: "FLAT",
}

var Coupon_CouponType_value = map[string]int32{
	"UNDEFINED": 0,
	"PERCENT":   1,
	"FLAT":      2,
}

func (x Coupon_CouponType) String() string {
	return proto.EnumName(Coupon_CouponType_name, int32(x))
}

func (Coupon_CouponType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{0, 0}
}

type Coupon_DayOfWeek int32

const (
	Coupon_DAY_OF_WEEK_UNSPECIFIED Coupon_DayOfWeek = 0
	Coupon_MONDAY                  Coupon_DayOfWeek = 1
	Coupon_TUESDAY                 Coupon_DayOfWeek = 2
	Coupon_WEDNESDAY               Coupon_DayOfWeek = 3
	Coupon_THURSDAY                Coupon_DayOfWeek = 4
	Coupon_FRIDAY                  Coupon_DayOfWeek = 5
	Coupon_SATURDAY                Coupon_DayOfWeek = 6
	Coupon_SUNDAY                  Coupon_DayOfWeek = 7
)

var Coupon_DayOfWeek_name = map[int32]string{
	0: "DAY_OF_WEEK_UNSPECIFIED",
	1: "MONDAY",
	2: "TUESDAY",
	3: "WEDNESDAY",
	4: "THURSDAY",
	5: "FRIDAY",
	6: "SATURDAY",
	7: "SUNDAY",
}

var Coupon_DayOfWeek_value = map[string]int32{
	"DAY_OF_WEEK_UNSPECIFIED": 0,
	"MONDAY":                  1,
	"TUESDAY":                 2,
	"WEDNESDAY":               3,
	"THURSDAY":                4,
	"FRIDAY":                  5,
	"SATURDAY":                6,
	"SUNDAY":                  7,
}

func (x Coupon_DayOfWeek) String() string {
	return proto.EnumName(Coupon_DayOfWeek_name, int32(x))
}

func (Coupon_DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{0, 1}
}

type Coupon struct {
	Id                   *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type                 Coupon_CouponType     `protobuf:"varint,5,opt,name=type,proto3,enum=coupon.Coupon_CouponType" json:"type,omitempty"`
	Status               *wrappers.BoolValue   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TimeFrom             *TimeOfDay            `protobuf:"bytes,7,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo               *TimeOfDay            `protobuf:"bytes,8,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	DateFrom             *Date                 `protobuf:"bytes,9,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               *Date                 `protobuf:"bytes,10,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Value                *wrappers.FloatValue  `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	FranchiseId          *wrappers.UInt64Value `protobuf:"bytes,12,opt,name=franchise_id,json=franchiseId,proto3" json:"franchise_id,omitempty"`
	Days                 []Coupon_DayOfWeek    `protobuf:"varint,13,rep,packed,name=days,proto3,enum=coupon.Coupon_DayOfWeek" json:"days,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Coupon) Reset()         { *m = Coupon{} }
func (m *Coupon) String() string { return proto.CompactTextString(m) }
func (*Coupon) ProtoMessage()    {}
func (*Coupon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{0}
}

func (m *Coupon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coupon.Unmarshal(m, b)
}
func (m *Coupon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coupon.Marshal(b, m, deterministic)
}
func (m *Coupon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coupon.Merge(m, src)
}
func (m *Coupon) XXX_Size() int {
	return xxx_messageInfo_Coupon.Size(m)
}
func (m *Coupon) XXX_DiscardUnknown() {
	xxx_messageInfo_Coupon.DiscardUnknown(m)
}

var xxx_messageInfo_Coupon proto.InternalMessageInfo

func (m *Coupon) GetId() *wrappers.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Coupon) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Coupon) GetCode() *wrappers.StringValue {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Coupon) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Coupon) GetType() Coupon_CouponType {
	if m != nil {
		return m.Type
	}
	return Coupon_UNDEFINED
}

func (m *Coupon) GetStatus() *wrappers.BoolValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Coupon) GetTimeFrom() *TimeOfDay {
	if m != nil {
		return m.TimeFrom
	}
	return nil
}

func (m *Coupon) GetTimeTo() *TimeOfDay {
	if m != nil {
		return m.TimeTo
	}
	return nil
}

func (m *Coupon) GetDateFrom() *Date {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *Coupon) GetDateTo() *Date {
	if m != nil {
		return m.DateTo
	}
	return nil
}

func (m *Coupon) GetValue() *wrappers.FloatValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Coupon) GetFranchiseId() *wrappers.UInt64Value {
	if m != nil {
		return m.FranchiseId
	}
	return nil
}

func (m *Coupon) GetDays() []Coupon_DayOfWeek {
	if m != nil {
		return m.Days
	}
	return nil
}

type Date struct {
	Year                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{1}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() *wrappers.UInt32Value {
	if m != nil {
		return m.Year
	}
	return nil
}

func (m *Date) GetMonth() *wrappers.UInt32Value {
	if m != nil {
		return m.Month
	}
	return nil
}

func (m *Date) GetDay() *wrappers.UInt32Value {
	if m != nil {
		return m.Day
	}
	return nil
}

type TimeOfDay struct {
	Hours                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes              *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TimeOfDay) Reset()         { *m = TimeOfDay{} }
func (m *TimeOfDay) String() string { return proto.CompactTextString(m) }
func (*TimeOfDay) ProtoMessage()    {}
func (*TimeOfDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{2}
}

func (m *TimeOfDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOfDay.Unmarshal(m, b)
}
func (m *TimeOfDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOfDay.Marshal(b, m, deterministic)
}
func (m *TimeOfDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOfDay.Merge(m, src)
}
func (m *TimeOfDay) XXX_Size() int {
	return xxx_messageInfo_TimeOfDay.Size(m)
}
func (m *TimeOfDay) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOfDay.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOfDay proto.InternalMessageInfo

func (m *TimeOfDay) GetHours() *wrappers.UInt32Value {
	if m != nil {
		return m.Hours
	}
	return nil
}

func (m *TimeOfDay) GetMinutes() *wrappers.UInt32Value {
	if m != nil {
		return m.Minutes
	}
	return nil
}

type CreateCouponRequest struct {
	Coupon               *Coupon  `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCouponRequest) Reset()         { *m = CreateCouponRequest{} }
func (m *CreateCouponRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCouponRequest) ProtoMessage()    {}
func (*CreateCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{3}
}

func (m *CreateCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCouponRequest.Unmarshal(m, b)
}
func (m *CreateCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCouponRequest.Marshal(b, m, deterministic)
}
func (m *CreateCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCouponRequest.Merge(m, src)
}
func (m *CreateCouponRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCouponRequest.Size(m)
}
func (m *CreateCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCouponRequest proto.InternalMessageInfo

func (m *CreateCouponRequest) GetCoupon() *Coupon {
	if m != nil {
		return m.Coupon
	}
	return nil
}

type UpdateCouponRequest struct {
	Coupon               *Coupon  `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCouponRequest) Reset()         { *m = UpdateCouponRequest{} }
func (m *UpdateCouponRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCouponRequest) ProtoMessage()    {}
func (*UpdateCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{4}
}

func (m *UpdateCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCouponRequest.Unmarshal(m, b)
}
func (m *UpdateCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCouponRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCouponRequest.Merge(m, src)
}
func (m *UpdateCouponRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCouponRequest.Size(m)
}
func (m *UpdateCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCouponRequest proto.InternalMessageInfo

func (m *UpdateCouponRequest) GetCoupon() *Coupon {
	if m != nil {
		return m.Coupon
	}
	return nil
}

type GetCouponRequest struct {
	Id                   *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetCouponRequest) Reset()         { *m = GetCouponRequest{} }
func (m *GetCouponRequest) String() string { return proto.CompactTextString(m) }
func (*GetCouponRequest) ProtoMessage()    {}
func (*GetCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{5}
}

func (m *GetCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCouponRequest.Unmarshal(m, b)
}
func (m *GetCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCouponRequest.Marshal(b, m, deterministic)
}
func (m *GetCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCouponRequest.Merge(m, src)
}
func (m *GetCouponRequest) XXX_Size() int {
	return xxx_messageInfo_GetCouponRequest.Size(m)
}
func (m *GetCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCouponRequest proto.InternalMessageInfo

func (m *GetCouponRequest) GetId() *wrappers.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteCouponRequest struct {
	Id                   *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeleteCouponRequest) Reset()         { *m = DeleteCouponRequest{} }
func (m *DeleteCouponRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCouponRequest) ProtoMessage()    {}
func (*DeleteCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{6}
}

func (m *DeleteCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCouponRequest.Unmarshal(m, b)
}
func (m *DeleteCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCouponRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCouponRequest.Merge(m, src)
}
func (m *DeleteCouponRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCouponRequest.Size(m)
}
func (m *DeleteCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCouponRequest proto.InternalMessageInfo

func (m *DeleteCouponRequest) GetId() *wrappers.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListCouponsRequest struct {
	Filter               *wrappers.StringValue `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListCouponsRequest) Reset()         { *m = ListCouponsRequest{} }
func (m *ListCouponsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCouponsRequest) ProtoMessage()    {}
func (*ListCouponsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{7}
}

func (m *ListCouponsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCouponsRequest.Unmarshal(m, b)
}
func (m *ListCouponsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCouponsRequest.Marshal(b, m, deterministic)
}
func (m *ListCouponsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCouponsRequest.Merge(m, src)
}
func (m *ListCouponsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCouponsRequest.Size(m)
}
func (m *ListCouponsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCouponsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCouponsRequest proto.InternalMessageInfo

func (m *ListCouponsRequest) GetFilter() *wrappers.StringValue {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListCouponsResponse struct {
	Coupons              []*Coupon `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListCouponsResponse) Reset()         { *m = ListCouponsResponse{} }
func (m *ListCouponsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCouponsResponse) ProtoMessage()    {}
func (*ListCouponsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{8}
}

func (m *ListCouponsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCouponsResponse.Unmarshal(m, b)
}
func (m *ListCouponsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCouponsResponse.Marshal(b, m, deterministic)
}
func (m *ListCouponsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCouponsResponse.Merge(m, src)
}
func (m *ListCouponsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCouponsResponse.Size(m)
}
func (m *ListCouponsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCouponsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCouponsResponse proto.InternalMessageInfo

func (m *ListCouponsResponse) GetCoupons() []*Coupon {
	if m != nil {
		return m.Coupons
	}
	return nil
}

type ListCouponsByFranchiseRequest struct {
	Id                   *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filter               *wrappers.StringValue `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListCouponsByFranchiseRequest) Reset()         { *m = ListCouponsByFranchiseRequest{} }
func (m *ListCouponsByFranchiseRequest) String() string { return proto.CompactTextString(m) }
func (*ListCouponsByFranchiseRequest) ProtoMessage()    {}
func (*ListCouponsByFranchiseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0be34d6f18a527f, []int{9}
}

func (m *ListCouponsByFranchiseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCouponsByFranchiseRequest.Unmarshal(m, b)
}
func (m *ListCouponsByFranchiseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCouponsByFranchiseRequest.Marshal(b, m, deterministic)
}
func (m *ListCouponsByFranchiseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCouponsByFranchiseRequest.Merge(m, src)
}
func (m *ListCouponsByFranchiseRequest) XXX_Size() int {
	return xxx_messageInfo_ListCouponsByFranchiseRequest.Size(m)
}
func (m *ListCouponsByFranchiseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCouponsByFranchiseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCouponsByFranchiseRequest proto.InternalMessageInfo

func (m *ListCouponsByFranchiseRequest) GetId() *wrappers.UInt64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ListCouponsByFranchiseRequest) GetFilter() *wrappers.StringValue {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterEnum("coupon.Coupon_CouponType", Coupon_CouponType_name, Coupon_CouponType_value)
	proto.RegisterEnum("coupon.Coupon_DayOfWeek", Coupon_DayOfWeek_name, Coupon_DayOfWeek_value)
	proto.RegisterType((*Coupon)(nil), "coupon.Coupon")
	proto.RegisterType((*Date)(nil), "coupon.Date")
	proto.RegisterType((*TimeOfDay)(nil), "coupon.TimeOfDay")
	proto.RegisterType((*CreateCouponRequest)(nil), "coupon.CreateCouponRequest")
	proto.RegisterType((*UpdateCouponRequest)(nil), "coupon.UpdateCouponRequest")
	proto.RegisterType((*GetCouponRequest)(nil), "coupon.GetCouponRequest")
	proto.RegisterType((*DeleteCouponRequest)(nil), "coupon.DeleteCouponRequest")
	proto.RegisterType((*ListCouponsRequest)(nil), "coupon.ListCouponsRequest")
	proto.RegisterType((*ListCouponsResponse)(nil), "coupon.ListCouponsResponse")
	proto.RegisterType((*ListCouponsByFranchiseRequest)(nil), "coupon.ListCouponsByFranchiseRequest")
}

func init() { proto.RegisterFile("proto/coupon.proto", fileDescriptor_f0be34d6f18a527f) }

var fileDescriptor_f0be34d6f18a527f = []byte{
	// 824 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x6d, 0x6f, 0xdb, 0x54,
	0x14, 0x6e, 0x5e, 0xea, 0x24, 0x27, 0x69, 0x15, 0x4e, 0xa5, 0x61, 0x12, 0x40, 0x95, 0xa5, 0xa1,
	0x82, 0x46, 0x0a, 0xde, 0x34, 0x3e, 0x95, 0xd1, 0xc5, 0x36, 0x0b, 0x8c, 0x64, 0x72, 0x6c, 0xaa,
	0x7d, 0x21, 0xf2, 0xe2, 0x9b, 0xd6, 0x22, 0xf6, 0x35, 0xf6, 0xcd, 0x26, 0x7f, 0x86, 0x9f, 0xc1,
	0xff, 0xe0, 0x2f, 0xf0, 0xb3, 0xd0, 0xbd, 0xb6, 0x53, 0x37, 0x71, 0x58, 0xd6, 0x4f, 0xee, 0xe9,
	0x79, 0x9e, 0xe7, 0x9c, 0x73, 0xcf, 0x73, 0x6f, 0x00, 0xc3, 0x88, 0x32, 0x7a, 0x3e, 0xa7, 0xab,
	0x90, 0x06, 0x03, 0x11, 0xa0, 0x94, 0x46, 0xbd, 0xfe, 0x35, 0xa5, 0xd7, 0x4b, 0x72, 0x2e, 0xfe,
	0xfb, 0x66, 0xb5, 0x38, 0x27, 0x7e, 0xc8, 0x92, 0x14, 0xd4, 0xfb, 0x7c, 0x33, 0xf9, 0x2e, 0x72,
	0xc2, 0x90, 0x44, 0x71, 0x9a, 0x57, 0xfe, 0x95, 0x40, 0x1a, 0x0a, 0x1d, 0x7c, 0x04, 0x55, 0xcf,
	0x95, 0x2b, 0xa7, 0x95, 0xb3, 0xb6, 0xfa, 0xe9, 0x20, 0xe5, 0x0d, 0x72, 0xde, 0xc0, 0x1e, 0x05,
	0xec, 0xe9, 0x93, 0x5f, 0x9d, 0xe5, 0x8a, 0x98, 0x55, 0xcf, 0xc5, 0x6f, 0xa0, 0x1e, 0x38, 0x3e,
	0x91, 0xab, 0x3b, 0xf0, 0x53, 0x16, 0x79, 0xc1, 0x75, 0x8a, 0x17, 0x48, 0xce, 0x98, 0x53, 0x97,
	0xc8, 0xb5, 0x7d, 0x18, 0x1c, 0x89, 0xdf, 0x43, 0xdb, 0x25, 0xf1, 0x3c, 0xf2, 0x42, 0xe6, 0xd1,
	0x40, 0xae, 0xef, 0x41, 0x2c, 0x12, 0xf0, 0x6b, 0xa8, 0xb3, 0x24, 0x24, 0xf2, 0xe1, 0x69, 0xe5,
	0xec, 0x58, 0xfd, 0x64, 0x90, 0x1d, 0xdf, 0xb0, 0xf8, 0xb1, 0x92, 0x90, 0x98, 0x02, 0x86, 0x2a,
	0x48, 0x31, 0x73, 0xd8, 0x2a, 0x96, 0x25, 0x51, 0xa9, 0xb7, 0x55, 0xe9, 0x39, 0xa5, 0xcb, 0xb4,
	0x4e, 0x86, 0xc4, 0x01, 0xb4, 0x98, 0xe7, 0x93, 0xd9, 0x22, 0xa2, 0xbe, 0xdc, 0x10, 0xb4, 0x8f,
	0xf2, 0x3a, 0x96, 0xe7, 0x93, 0xc9, 0x42, 0x73, 0x12, 0xb3, 0xc9, 0x31, 0x46, 0x44, 0x7d, 0xfc,
	0x0a, 0x1a, 0x02, 0xcf, 0xa8, 0xdc, 0xdc, 0x85, 0x96, 0x38, 0xc2, 0xa2, 0xf8, 0x25, 0xb4, 0x5c,
	0x87, 0x65, 0xda, 0x2d, 0x81, 0xee, 0xe4, 0x68, 0xcd, 0x61, 0xc4, 0x6c, 0xf2, 0xb4, 0x90, 0x7d,
	0x08, 0x0d, 0x01, 0x65, 0x54, 0x86, 0x12, 0xa0, 0xc4, 0x93, 0x16, 0xc5, 0x6f, 0xe1, 0xf0, 0x2d,
	0x6f, 0x5f, 0x6e, 0x0b, 0x50, 0x7f, 0x6b, 0x40, 0x63, 0x49, 0x1d, 0x96, 0x4e, 0x98, 0x22, 0xf1,
	0x19, 0x74, 0x16, 0x91, 0x13, 0xcc, 0x6f, 0xbc, 0x98, 0xcc, 0x3c, 0x57, 0xee, 0xec, 0xe1, 0x8f,
	0xf6, 0x9a, 0x31, 0x72, 0xf1, 0x11, 0xd4, 0x5d, 0x27, 0x89, 0xe5, 0xa3, 0xd3, 0xda, 0xd9, 0xb1,
	0x2a, 0x6f, 0x2c, 0x41, 0x73, 0x92, 0xc9, 0xe2, 0x8a, 0x90, 0xdf, 0x4d, 0x81, 0x52, 0x54, 0x80,
	0xdb, 0xbd, 0xe0, 0x11, 0xb4, 0xec, 0xb1, 0xa6, 0x1b, 0xa3, 0xb1, 0xae, 0x75, 0x0f, 0xb0, 0x0d,
	0x8d, 0x57, 0xba, 0x39, 0xd4, 0xc7, 0x56, 0xb7, 0x82, 0x4d, 0xa8, 0x1b, 0x2f, 0x2f, 0xad, 0x6e,
	0x55, 0xf9, 0xab, 0x02, 0xad, 0xb5, 0x0e, 0xf6, 0xe1, 0x63, 0xed, 0xf2, 0xf5, 0x6c, 0x62, 0xcc,
	0xae, 0x74, 0xfd, 0xe7, 0x99, 0x3d, 0x9e, 0xbe, 0xd2, 0x87, 0x23, 0x63, 0x24, 0x14, 0x00, 0xa4,
	0x5f, 0x26, 0x63, 0xed, 0xf2, 0x75, 0xb7, 0xc2, 0xd5, 0x2c, 0x5b, 0x9f, 0xf2, 0xa0, 0xca, 0x2b,
	0x5d, 0xe9, 0xda, 0x38, 0x0d, 0x6b, 0xd8, 0x81, 0xa6, 0xf5, 0xc2, 0x36, 0x45, 0x54, 0xe7, 0x2c,
	0xc3, 0x1c, 0xf1, 0xbf, 0x0f, 0x79, 0x66, 0x7a, 0x69, 0xd9, 0x26, 0x8f, 0x24, 0x9e, 0x99, 0xda,
	0x42, 0xaf, 0xa1, 0xfc, 0x5d, 0x81, 0x3a, 0x3f, 0x6d, 0x6e, 0xf4, 0x84, 0x38, 0xd1, 0xff, 0x5e,
	0xa5, 0xc7, 0x6a, 0x66, 0x74, 0x8e, 0x44, 0x15, 0x0e, 0x7d, 0x1a, 0xb0, 0x9b, 0x9d, 0xb7, 0xa9,
	0x48, 0x49, 0xa1, 0x38, 0x80, 0x9a, 0xeb, 0x24, 0x3b, 0x6f, 0x53, 0x91, 0xc1, 0x81, 0xca, 0x3b,
	0x68, 0xad, 0x2d, 0xc6, 0x0b, 0xde, 0xd0, 0x55, 0x14, 0xef, 0xd5, 0x63, 0x0a, 0xc5, 0xa7, 0xd0,
	0xf0, 0xbd, 0x60, 0xc5, 0x48, 0xbc, 0x57, 0x9b, 0x39, 0x58, 0xb9, 0x80, 0x93, 0x61, 0x44, 0x1c,
	0x46, 0xd2, 0xc5, 0x9a, 0xe4, 0x8f, 0x15, 0x89, 0x19, 0x7e, 0x01, 0xd9, 0x03, 0x96, 0xf5, 0x70,
	0x7c, 0xd7, 0x19, 0x66, 0x96, 0xe5, 0x74, 0x3b, 0x74, 0xef, 0x4d, 0xff, 0x01, 0xba, 0x3f, 0x12,
	0x76, 0x97, 0xfb, 0x41, 0x2f, 0x9d, 0x32, 0x84, 0x13, 0x8d, 0x2c, 0xc9, 0x66, 0x03, 0x1f, 0x26,
	0xf2, 0x13, 0xe0, 0x4b, 0x2f, 0xce, 0xfa, 0x88, 0x73, 0x8d, 0x27, 0x20, 0x2d, 0xbc, 0x25, 0x23,
	0xbb, 0xbd, 0x52, 0x7c, 0xdb, 0x32, 0xac, 0xf2, 0x0c, 0x4e, 0xee, 0x68, 0xc5, 0xfc, 0x43, 0xf0,
	0x0c, 0x1a, 0xe9, 0xcc, 0x7c, 0xab, 0xb5, 0x92, 0x23, 0xc9, 0xd3, 0xca, 0x9f, 0x15, 0xf8, 0xac,
	0xa0, 0xf0, 0x3c, 0x31, 0xf2, 0xfb, 0x7a, 0xaf, 0xe1, 0x0a, 0x63, 0x54, 0xf7, 0x1f, 0x43, 0xfd,
	0xa7, 0x06, 0x47, 0x69, 0x07, 0x53, 0x12, 0xbd, 0xf5, 0xe6, 0x04, 0x2f, 0xa0, 0x53, 0x74, 0x0a,
	0xf6, 0xd7, 0x03, 0x6c, 0xfb, 0xa7, 0xb7, 0x31, 0x9d, 0x72, 0x80, 0xdf, 0x41, 0x6b, 0xbd, 0x6a,
	0x5c, 0x3f, 0x34, 0x9b, 0xdb, 0x2f, 0x21, 0x5e, 0x40, 0xa7, 0x68, 0xb1, 0xdb, 0xba, 0x25, 0xc6,
	0x2b, 0xa1, 0xeb, 0xd0, 0x29, 0x1a, 0xe4, 0x96, 0x5e, 0x62, 0x9b, 0xde, 0x83, 0xad, 0xb3, 0xd1,
	0xf9, 0xcf, 0xb5, 0x72, 0x80, 0x2f, 0xa0, 0x5d, 0x58, 0x0a, 0xf6, 0x72, 0x95, 0x6d, 0xdf, 0xf4,
	0xfa, 0xa5, 0xb9, 0xd4, 0x07, 0xca, 0x01, 0xfe, 0x06, 0x0f, 0xca, 0xd7, 0x8b, 0x0f, 0x4b, 0x88,
	0xdb, 0xeb, 0x7f, 0x8f, 0xfe, 0x1b, 0x49, 0xf4, 0xfe, 0xf8, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x32, 0xd5, 0xf7, 0x25, 0x96, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CouponServiceClient interface {
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error)
	ListCouponsByFranchise(ctx context.Context, in *ListCouponsByFranchiseRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error)
}

type couponServiceClient struct {
	cc *grpc.ClientConn
}

func NewCouponServiceClient(cc *grpc.ClientConn) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	out := new(Coupon)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/CreateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	out := new(Coupon)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/GetCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	out := new(Coupon)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/UpdateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/DeleteCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error) {
	out := new(ListCouponsResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/ListCoupons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListCouponsByFranchise(ctx context.Context, in *ListCouponsByFranchiseRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error) {
	out := new(ListCouponsResponse)
	err := c.cc.Invoke(ctx, "/coupon.CouponService/ListCouponsByFranchise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
type CouponServiceServer interface {
	CreateCoupon(context.Context, *CreateCouponRequest) (*Coupon, error)
	GetCoupon(context.Context, *GetCouponRequest) (*Coupon, error)
	UpdateCoupon(context.Context, *UpdateCouponRequest) (*Coupon, error)
	DeleteCoupon(context.Context, *DeleteCouponRequest) (*empty.Empty, error)
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsResponse, error)
	ListCouponsByFranchise(context.Context, *ListCouponsByFranchiseRequest) (*ListCouponsResponse, error)
}

func RegisterCouponServiceServer(s *grpc.Server, srv CouponServiceServer) {
	s.RegisterService(&_CouponService_serviceDesc, srv)
}

func _CouponService_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/CreateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/GetCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetCoupon(ctx, req.(*GetCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UpdateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UpdateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/UpdateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UpdateCoupon(ctx, req.(*UpdateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_DeleteCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).DeleteCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/DeleteCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).DeleteCoupon(ctx, req.(*DeleteCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/ListCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCoupons(ctx, req.(*ListCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListCouponsByFranchise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsByFranchiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCouponsByFranchise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.CouponService/ListCouponsByFranchise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCouponsByFranchise(ctx, req.(*ListCouponsByFranchiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CouponService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _CouponService_CreateCoupon_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _CouponService_GetCoupon_Handler,
		},
		{
			MethodName: "UpdateCoupon",
			Handler:    _CouponService_UpdateCoupon_Handler,
		},
		{
			MethodName: "DeleteCoupon",
			Handler:    _CouponService_DeleteCoupon_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _CouponService_ListCoupons_Handler,
		},
		{
			MethodName: "ListCouponsByFranchise",
			Handler:    _CouponService_ListCouponsByFranchise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coupon.proto",
}
