// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discount.proto

package coupon_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coupon_CouponType int32

const (
	Coupon_PERCENT Coupon_CouponType = 0
	Coupon_FLAT    Coupon_CouponType = 1
)

var Coupon_CouponType_name = map[int32]string{
	0: "PERCENT",
	1: "FLAT",
}

var Coupon_CouponType_value = map[string]int32{
	"PERCENT": 0,
	"FLAT":    1,
}

func (x Coupon_CouponType) String() string {
	return proto.EnumName(Coupon_CouponType_name, int32(x))
}

func (Coupon_CouponType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{0, 0}
}

type Coupon_DayOfWeek int32

const (
	Coupon_MONDAY    Coupon_DayOfWeek = 0
	Coupon_TUESDAY   Coupon_DayOfWeek = 1
	Coupon_WEDNESDAY Coupon_DayOfWeek = 2
	Coupon_THURSDAY  Coupon_DayOfWeek = 3
	Coupon_FRIDAY    Coupon_DayOfWeek = 4
	Coupon_SATURDAY  Coupon_DayOfWeek = 5
	Coupon_SUNDAY    Coupon_DayOfWeek = 6
)

var Coupon_DayOfWeek_name = map[int32]string{
	0: "MONDAY",
	1: "TUESDAY",
	2: "WEDNESDAY",
	3: "THURSDAY",
	4: "FRIDAY",
	5: "SATURDAY",
	6: "SUNDAY",
}

var Coupon_DayOfWeek_value = map[string]int32{
	"MONDAY":    0,
	"TUESDAY":   1,
	"WEDNESDAY": 2,
	"THURSDAY":  3,
	"FRIDAY":    4,
	"SATURDAY":  5,
	"SUNDAY":    6,
}

func (x Coupon_DayOfWeek) String() string {
	return proto.EnumName(Coupon_DayOfWeek_name, int32(x))
}

func (Coupon_DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{0, 1}
}

type Coupon struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string               `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type                 Coupon_CouponType    `protobuf:"varint,5,opt,name=type,proto3,enum=coupon_proto.Coupon_CouponType" json:"type,omitempty"`
	Status               bool                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	TimeFrom             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo               *timestamp.Timestamp `protobuf:"bytes,8,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	DateFrom             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               *timestamp.Timestamp `protobuf:"bytes,10,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Days                 []Coupon_DayOfWeek   `protobuf:"varint,11,rep,packed,name=days,proto3,enum=coupon_proto.Coupon_DayOfWeek" json:"days,omitempty"`
	Value                float32              `protobuf:"fixed32,12,opt,name=value,proto3" json:"value,omitempty"`
	FranchiseId          uint64               `protobuf:"varint,13,opt,name=franchise_id,json=franchiseId,proto3" json:"franchise_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Coupon) Reset()         { *m = Coupon{} }
func (m *Coupon) String() string { return proto.CompactTextString(m) }
func (*Coupon) ProtoMessage()    {}
func (*Coupon) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{0}
}

func (m *Coupon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coupon.Unmarshal(m, b)
}
func (m *Coupon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coupon.Marshal(b, m, deterministic)
}
func (m *Coupon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coupon.Merge(m, src)
}
func (m *Coupon) XXX_Size() int {
	return xxx_messageInfo_Coupon.Size(m)
}
func (m *Coupon) XXX_DiscardUnknown() {
	xxx_messageInfo_Coupon.DiscardUnknown(m)
}

var xxx_messageInfo_Coupon proto.InternalMessageInfo

func (m *Coupon) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Coupon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Coupon) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Coupon) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Coupon) GetType() Coupon_CouponType {
	if m != nil {
		return m.Type
	}
	return Coupon_PERCENT
}

func (m *Coupon) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Coupon) GetTimeFrom() *timestamp.Timestamp {
	if m != nil {
		return m.TimeFrom
	}
	return nil
}

func (m *Coupon) GetTimeTo() *timestamp.Timestamp {
	if m != nil {
		return m.TimeTo
	}
	return nil
}

func (m *Coupon) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *Coupon) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

func (m *Coupon) GetDays() []Coupon_DayOfWeek {
	if m != nil {
		return m.Days
	}
	return nil
}

func (m *Coupon) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Coupon) GetFranchiseId() uint64 {
	if m != nil {
		return m.FranchiseId
	}
	return 0
}

type CreateCouponRequest struct {
	Coupon               *Coupon  `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCouponRequest) Reset()         { *m = CreateCouponRequest{} }
func (m *CreateCouponRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCouponRequest) ProtoMessage()    {}
func (*CreateCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{1}
}

func (m *CreateCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCouponRequest.Unmarshal(m, b)
}
func (m *CreateCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCouponRequest.Marshal(b, m, deterministic)
}
func (m *CreateCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCouponRequest.Merge(m, src)
}
func (m *CreateCouponRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCouponRequest.Size(m)
}
func (m *CreateCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCouponRequest proto.InternalMessageInfo

func (m *CreateCouponRequest) GetCoupon() *Coupon {
	if m != nil {
		return m.Coupon
	}
	return nil
}

type UpdateCouponRequest struct {
	Coupon               *Coupon  `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCouponRequest) Reset()         { *m = UpdateCouponRequest{} }
func (m *UpdateCouponRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCouponRequest) ProtoMessage()    {}
func (*UpdateCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{2}
}

func (m *UpdateCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCouponRequest.Unmarshal(m, b)
}
func (m *UpdateCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCouponRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCouponRequest.Merge(m, src)
}
func (m *UpdateCouponRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCouponRequest.Size(m)
}
func (m *UpdateCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCouponRequest proto.InternalMessageInfo

func (m *UpdateCouponRequest) GetCoupon() *Coupon {
	if m != nil {
		return m.Coupon
	}
	return nil
}

type GetCouponRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCouponRequest) Reset()         { *m = GetCouponRequest{} }
func (m *GetCouponRequest) String() string { return proto.CompactTextString(m) }
func (*GetCouponRequest) ProtoMessage()    {}
func (*GetCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{3}
}

func (m *GetCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCouponRequest.Unmarshal(m, b)
}
func (m *GetCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCouponRequest.Marshal(b, m, deterministic)
}
func (m *GetCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCouponRequest.Merge(m, src)
}
func (m *GetCouponRequest) XXX_Size() int {
	return xxx_messageInfo_GetCouponRequest.Size(m)
}
func (m *GetCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCouponRequest proto.InternalMessageInfo

func (m *GetCouponRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCouponRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCouponRequest) Reset()         { *m = DeleteCouponRequest{} }
func (m *DeleteCouponRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCouponRequest) ProtoMessage()    {}
func (*DeleteCouponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{4}
}

func (m *DeleteCouponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCouponRequest.Unmarshal(m, b)
}
func (m *DeleteCouponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCouponRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCouponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCouponRequest.Merge(m, src)
}
func (m *DeleteCouponRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCouponRequest.Size(m)
}
func (m *DeleteCouponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCouponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCouponRequest proto.InternalMessageInfo

func (m *DeleteCouponRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListCouponsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCouponsRequest) Reset()         { *m = ListCouponsRequest{} }
func (m *ListCouponsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCouponsRequest) ProtoMessage()    {}
func (*ListCouponsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{5}
}

func (m *ListCouponsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCouponsRequest.Unmarshal(m, b)
}
func (m *ListCouponsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCouponsRequest.Marshal(b, m, deterministic)
}
func (m *ListCouponsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCouponsRequest.Merge(m, src)
}
func (m *ListCouponsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCouponsRequest.Size(m)
}
func (m *ListCouponsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCouponsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCouponsRequest proto.InternalMessageInfo

type ListCouponsResponse struct {
	Coupons              []*Coupon `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListCouponsResponse) Reset()         { *m = ListCouponsResponse{} }
func (m *ListCouponsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCouponsResponse) ProtoMessage()    {}
func (*ListCouponsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78985be6a51b316f, []int{6}
}

func (m *ListCouponsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCouponsResponse.Unmarshal(m, b)
}
func (m *ListCouponsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCouponsResponse.Marshal(b, m, deterministic)
}
func (m *ListCouponsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCouponsResponse.Merge(m, src)
}
func (m *ListCouponsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCouponsResponse.Size(m)
}
func (m *ListCouponsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCouponsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCouponsResponse proto.InternalMessageInfo

func (m *ListCouponsResponse) GetCoupons() []*Coupon {
	if m != nil {
		return m.Coupons
	}
	return nil
}

func init() {
	proto.RegisterEnum("coupon_proto.Coupon_CouponType", Coupon_CouponType_name, Coupon_CouponType_value)
	proto.RegisterEnum("coupon_proto.Coupon_DayOfWeek", Coupon_DayOfWeek_name, Coupon_DayOfWeek_value)
	proto.RegisterType((*Coupon)(nil), "coupon_proto.Coupon")
	proto.RegisterType((*CreateCouponRequest)(nil), "coupon_proto.CreateCouponRequest")
	proto.RegisterType((*UpdateCouponRequest)(nil), "coupon_proto.UpdateCouponRequest")
	proto.RegisterType((*GetCouponRequest)(nil), "coupon_proto.GetCouponRequest")
	proto.RegisterType((*DeleteCouponRequest)(nil), "coupon_proto.DeleteCouponRequest")
	proto.RegisterType((*ListCouponsRequest)(nil), "coupon_proto.ListCouponsRequest")
	proto.RegisterType((*ListCouponsResponse)(nil), "coupon_proto.ListCouponsResponse")
}

func init() { proto.RegisterFile("discount.proto", fileDescriptor_78985be6a51b316f) }

var fileDescriptor_78985be6a51b316f = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x8d, 0xc1, 0x18, 0x18, 0x3b, 0x08, 0x4d, 0xa2, 0x68, 0xc5, 0x27, 0x7d, 0x71, 0x5c, 0x55,
	0xf2, 0xa1, 0x72, 0x24, 0x72, 0xe8, 0x19, 0x01, 0x49, 0x23, 0xa5, 0x49, 0xb5, 0x18, 0x45, 0x3d,
	0x45, 0x0e, 0x5e, 0x52, 0xab, 0x81, 0x75, 0xbd, 0x4b, 0x24, 0xce, 0x95, 0xfa, 0xbb, 0xab, 0xdd,
	0x85, 0x94, 0x38, 0xa4, 0x1c, 0x7a, 0xf2, 0xce, 0xcc, 0x9b, 0xf7, 0x66, 0xdf, 0xd8, 0x86, 0x56,
	0x9a, 0x89, 0x09, 0x5f, 0xcc, 0x65, 0x94, 0x17, 0x5c, 0x72, 0xf4, 0x26, 0x7c, 0x91, 0xf3, 0xf9,
	0x9d, 0x8e, 0x3a, 0xc7, 0x0f, 0x9c, 0x3f, 0x3c, 0xb2, 0x53, 0x1d, 0xdd, 0x2f, 0xa6, 0xa7, 0x32,
	0x9b, 0x31, 0x21, 0x93, 0x59, 0x6e, 0xe0, 0x9d, 0xff, 0xca, 0x00, 0x36, 0xcb, 0xe5, 0xd2, 0x14,
	0x83, 0x5f, 0x35, 0x70, 0xfa, 0x9a, 0x0e, 0x5b, 0x50, 0xc9, 0x52, 0x62, 0xf9, 0x56, 0x68, 0xd3,
	0x4a, 0x96, 0x22, 0x82, 0x3d, 0x4f, 0x66, 0x8c, 0x54, 0x7c, 0x2b, 0x6c, 0x52, 0x7d, 0x56, 0xb9,
	0x09, 0x4f, 0x19, 0xa9, 0x9a, 0x9c, 0x3a, 0xa3, 0x0f, 0x6e, 0xca, 0xc4, 0xa4, 0xc8, 0x72, 0x99,
	0xf1, 0x39, 0xb1, 0x75, 0x69, 0x33, 0x85, 0x67, 0x60, 0xcb, 0x65, 0xce, 0x48, 0xcd, 0xb7, 0xc2,
	0x56, 0xf7, 0x38, 0xda, 0x9c, 0x3f, 0x32, 0xea, 0xab, 0x47, 0xbc, 0xcc, 0x19, 0xd5, 0x60, 0x3c,
	0x02, 0x47, 0xc8, 0x44, 0x2e, 0x04, 0x71, 0x7c, 0x2b, 0x6c, 0xd0, 0x55, 0x84, 0x1f, 0xa1, 0xa9,
	0x6e, 0x78, 0x37, 0x2d, 0xf8, 0x8c, 0xd4, 0x7d, 0x2b, 0x74, 0xbb, 0x9d, 0xc8, 0x5c, 0x31, 0x5a,
	0x5f, 0x31, 0x8a, 0xd7, 0x1e, 0xd0, 0x86, 0x02, 0x9f, 0x17, 0x7c, 0x86, 0x67, 0x50, 0xd7, 0x8d,
	0x92, 0x93, 0xc6, 0xce, 0x36, 0x47, 0x41, 0x63, 0xae, 0xd4, 0xd2, 0x44, 0xae, 0xd4, 0x9a, 0xbb,
	0xd5, 0x14, 0x78, 0xad, 0xa6, 0x1b, 0x25, 0x27, 0xb0, 0x5b, 0x4d, 0x41, 0x63, 0x8e, 0x5d, 0xb0,
	0xd3, 0x64, 0x29, 0x88, 0xeb, 0x57, 0xc3, 0x56, 0xf7, 0xff, 0xad, 0x46, 0x0d, 0x92, 0xe5, 0xcd,
	0xf4, 0x96, 0xb1, 0xef, 0x54, 0x63, 0xf1, 0x10, 0x6a, 0x4f, 0xc9, 0xe3, 0x82, 0x11, 0xcf, 0xb7,
	0xc2, 0x0a, 0x35, 0x01, 0x9e, 0x80, 0x37, 0x2d, 0x92, 0xf9, 0xe4, 0x5b, 0x26, 0xd8, 0x5d, 0x96,
	0x92, 0x7d, 0xbd, 0x56, 0xf7, 0x39, 0x77, 0x99, 0x06, 0xef, 0x00, 0xfe, 0x98, 0x8e, 0x2e, 0xd4,
	0xbf, 0x0c, 0x69, 0x7f, 0x78, 0x1d, 0xb7, 0xf7, 0xb0, 0x01, 0xf6, 0xf9, 0x55, 0x2f, 0x6e, 0x5b,
	0xc1, 0x03, 0x34, 0x9f, 0x05, 0x11, 0xc0, 0xf9, 0x7c, 0x73, 0x3d, 0xe8, 0x7d, 0x6d, 0xef, 0x29,
	0x7c, 0x3c, 0x1e, 0x8e, 0x54, 0x60, 0xe1, 0x3e, 0x34, 0x6f, 0x87, 0x83, 0x6b, 0x13, 0x56, 0xd0,
	0x83, 0x46, 0xfc, 0x69, 0x4c, 0x75, 0x54, 0x55, 0x5d, 0xe7, 0xf4, 0x52, 0x9d, 0x6d, 0x55, 0x19,
	0xf5, 0xe2, 0x31, 0x55, 0x51, 0x4d, 0x55, 0x46, 0x63, 0xcd, 0xe7, 0x04, 0x7d, 0x38, 0xe8, 0x17,
	0x2c, 0x91, 0xcc, 0xcc, 0x44, 0xd9, 0x8f, 0x05, 0x13, 0x12, 0x3f, 0x80, 0x63, 0x4c, 0xd0, 0x2f,
	0xa6, 0xdb, 0x3d, 0xdc, 0xe6, 0x09, 0x5d, 0x61, 0x14, 0xc9, 0x38, 0x4f, 0xff, 0x91, 0x24, 0x80,
	0xf6, 0x05, 0x93, 0x2f, 0x19, 0x4a, 0xdf, 0x46, 0xf0, 0x1e, 0x0e, 0x06, 0xec, 0x91, 0x95, 0x85,
	0xca, 0xb0, 0x43, 0xc0, 0xab, 0x4c, 0xac, 0xb8, 0xc4, 0x0a, 0x15, 0x0c, 0xe1, 0xe0, 0x45, 0x56,
	0xa8, 0x07, 0xc3, 0x08, 0xea, 0x66, 0x02, 0x41, 0x2c, 0xbf, 0xfa, 0xe6, 0x98, 0x6b, 0x50, 0xf7,
	0x67, 0x15, 0xf6, 0x4d, 0x6e, 0xc4, 0x8a, 0xa7, 0x6c, 0xc2, 0xf0, 0x02, 0xbc, 0x4d, 0x0f, 0xf1,
	0xa4, 0x44, 0xf0, 0xda, 0xdf, 0xce, 0x56, 0x0d, 0xec, 0x41, 0xf3, 0xd9, 0x02, 0x2c, 0xbd, 0x86,
	0x65, 0x6f, 0xde, 0xa0, 0xb8, 0x00, 0x6f, 0x73, 0x15, 0xe5, 0x59, 0xb6, 0xac, 0xe9, 0x0d, 0xa2,
	0x4b, 0xf0, 0x36, 0xad, 0x2e, 0x13, 0x6d, 0x59, 0x43, 0xe7, 0xe8, 0xd5, 0xa7, 0x36, 0x54, 0xbf,
	0x3c, 0xa4, 0xe0, 0x6e, 0x18, 0x8f, 0xfe, 0x4b, 0xa6, 0xd7, 0x9b, 0xea, 0x9c, 0xfc, 0x05, 0x61,
	0xb6, 0x76, 0xef, 0xe8, 0xd2, 0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xbd, 0x2a, 0xcd,
	0xa5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CouponServiceClient interface {
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*Coupon, error)
	DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error)
}

type couponServiceClient struct {
	cc *grpc.ClientConn
}

func NewCouponServiceClient(cc *grpc.ClientConn) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	out := new(Coupon)
	err := c.cc.Invoke(ctx, "/coupon_proto.CouponService/CreateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	out := new(Coupon)
	err := c.cc.Invoke(ctx, "/coupon_proto.CouponService/GetCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*Coupon, error) {
	out := new(Coupon)
	err := c.cc.Invoke(ctx, "/coupon_proto.CouponService/UpdateCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/coupon_proto.CouponService/DeleteCoupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsResponse, error) {
	out := new(ListCouponsResponse)
	err := c.cc.Invoke(ctx, "/coupon_proto.CouponService/ListCoupons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
type CouponServiceServer interface {
	CreateCoupon(context.Context, *CreateCouponRequest) (*Coupon, error)
	GetCoupon(context.Context, *GetCouponRequest) (*Coupon, error)
	UpdateCoupon(context.Context, *UpdateCouponRequest) (*Coupon, error)
	DeleteCoupon(context.Context, *DeleteCouponRequest) (*empty.Empty, error)
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsResponse, error)
}

func RegisterCouponServiceServer(s *grpc.Server, srv CouponServiceServer) {
	s.RegisterService(&_CouponService_serviceDesc, srv)
}

func _CouponService_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon_proto.CouponService/CreateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon_proto.CouponService/GetCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetCoupon(ctx, req.(*GetCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UpdateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UpdateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon_proto.CouponService/UpdateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UpdateCoupon(ctx, req.(*UpdateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_DeleteCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).DeleteCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon_proto.CouponService/DeleteCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).DeleteCoupon(ctx, req.(*DeleteCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon_proto.CouponService/ListCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCoupons(ctx, req.(*ListCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CouponService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coupon_proto.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _CouponService_CreateCoupon_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _CouponService_GetCoupon_Handler,
		},
		{
			MethodName: "UpdateCoupon",
			Handler:    _CouponService_UpdateCoupon_Handler,
		},
		{
			MethodName: "DeleteCoupon",
			Handler:    _CouponService_DeleteCoupon_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _CouponService_ListCoupons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discount.proto",
}
